version: "3.8"

services:
  react:
    container_name: react

    env_file: ./.env
    build:
      context: .\front
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - front
  proxy:
    container_name: "proxy"
    build: .\back\proxy
    env_file: ./.env
    environment:
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - NOTIFICATION_DOCKER_PORT=$NOTIFICATION_DOCKER_PORT
      - GAME_DOCKER_PORT=$GAME_DOCKER_PORT
      - PROXY_DOCKER_PORT=$PROXY_DOCKER_PORT
      - REACT_DOCKER_PORT=$REACT_DOCKER_PORT
      - USER_DOCKER_PORT=$USER_DOCKER_PORT
      
    ports:
      - $PROXY_LOCAL_PORT:$PROXY_DOCKER_PORT        
    networks:
      - back
      - front
          
  notification-service:
      container_name: notification-service        
      build: .\back\microservices\notification_service
      command: npm start
      env_file: ./.env
      ports:
        - $NOTIFICATION_LOCAL_PORT:$NOTIFICATION_DOCKER_PORT
      networks:
        - back

  game-service:
          container_name: game-service
          build: .\back\microservices\game_service
          command: npm start
          env_file: ./.env
          ports:
            - $GAME_LOCAL_PORT:$GAME_DOCKER_PORT
          networks:
            - back

  user-service:
          container_name: user-service
          build: .\back\microservices\user_service
          env_file: ./.env
          ports:
            - $USER_LOCAL_PORT:$USER_DOCKER_PORT
          networks:
            - back
      
networks:
  back:
  front: